// Generated by convrom.exe
// ROM 8x8 Font bios mode 10
// mtrojer@arrownordic.com
// $WCREV$

#ifdef __cplusplus

extern "C" const UNS_16 font_rom8x16_bits[4096];

#else

extern const UNS_16 font_rom8x16_bits[4096];

#endif
